fp = r'D:\KU-Assignment\IVF\review2\AIR_Review_Package\github\_build\build_site.py'
src = open(fp,encoding='utf-8').read()
start = src.index('def clean_tex(t):')
end = src.index('CITE_RE =')
B = chr(92)
# Build each regex with explicit backslash chars to avoid quote-escape ambiguity
lines = []
lines.append('def clean_tex(t):')
lines.append("    t = re.sub(r'(?<!" + B + ")%.*', '', t)")
lines.append('    for _ in range(8):')
lines.append('        depth=0; cut=-1')
lines.append("        for m in re.finditer(r'" + B + "(begin" + B + "{|end" + B + "{[^}]*" + B + "}|begingroup|endgroup)', t):")
lines.append('            tok=m.group(1)')
lines.append("            if tok.startswith('begin'): depth+=1")
lines.append('            else:')
lines.append('                depth-=1')
lines.append('                if depth<0: cut=m.end(); break')
lines.append('        if cut<0: break')
lines.append('        t=t[cut:]')
# strip envs
for env in ['longtable','sidewaystable','tabularx','tabular','figure','minipage','table','equation','align','sidewaysfigure']:
    lines.append("    t = re.sub(r'" + B + "begin" + B + "{?" + env + "*?" + B + "}(?:[^}]*" + B + "})?[" + B + "s" + B + "S]*?" + B + "end" + B + "{?" + env + "*?" + B + "}', ' ', t)")
lines.append("    t = re.sub(r'" + B + "begingroup[" + B + "s" + B + "S]*?" + B + "endgroup', ' ', t)")
lines.append("    t = re.sub(r'" + B + "bgroup[" + B + "s" + B + "S]*?" + B + "egroup', ' ', t)")
lines.append("    t = re.sub(r'" + B + "(?:setlength|renewcommand|setcounter|addtocounter|newcommand|providecommand|def|let)" + B + "{[^}]*" + B + "}" + B + "{[^}]*" + B + "}', ' ', t)")
lines.append("    t = re.sub(r'" + B + "(?:setlength|renewcommand|setcounter)" + B + "{[^}]*" + B + "}', ' ', t)")
lines.append("    t = re.sub(r'" + B + "cite[tp]?(?:" + B + "[[^" + B + "]]" + B + "])*" + B + "{([^}]*)" + B + "}', r'[@" + B + "1]', t)")
lines.append("    t = re.sub(r'" + B + "(?:label|ref|eqref|autoref|pageref)" + B + "{[^}]*" + B + "}', '', t)")
lines.append("    t = re.sub(r'" + B + "(?:textbf|textit|emph|texttt|textsc|underline)" + B + "{([^}]*)" + B + "}', r'" + B + "1', t)")
lines.append("    t = re.sub(r'" + B + "(sub)*section*?" + B + "{[^}]*" + B + "}', '', t)")
lines.append("    t = re.sub(r'" + B + "(?:begin|end)" + B + "{[^}]*" + B + "}', ' ', t)")
lines.append("    t = re.sub(r'" + B + "[a-zA-Z]+" + B + "*?(?:" + B + "[[^" + B + "]]" + B + "])?', ' ', t)")
lines.append("    t = t.replace('~',' ').replace('" + B + "%','%').replace('" + B + "&','&').replace('" + B + "_','_').replace('" + B + "$','$')")
lines.append("    t = re.sub(r'[{}]', '', t)")
lines.append("    t = re.sub(r'" + B + "s+', ' ', t).strip()")
lines.append('    return t')
lines.append('')
newf = chr(10).join(lines)
open(fp,'w',encoding='utf-8').write(src[:start]+newf+src[end:])
print('rewrote clean_tex, lines:', len(lines))
